# Create a GitHub action to email a report from a file at 6 a.m. daily.

name: Deploy App

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send email
      run: |
        echo "Sending email..."
        echo "Hello, this is your daily report." > report.txt
        echo "Have a great day!" >> report.txt
        mail -s "Daily Report"